### ISSUE TITLE
zapstore.dev not working

### ISSUE THREAD

**Issue by Giszmo** [zapstore/zapstore#169]
This repo lists zapstore.dev as its website yet that site forwards to https://nostr.band/npub10r8xl2njyepcw2zwv3a6dyufj4e4ajx86hz6v4ehu4gnpupxxp7stjt2p8 which in turn doesn't load much.

![image](https://github.com/user-attachments/assets/f4d6fe45-b3c8-4be4-bb4b-a9f05272275c)

The dev console shows this on Firefox:

```
22:42:16.204 router npub10r8xl2njyepcw2zwv3a6dyufj4e4ajx86hz6v4ehu4gnpupxxp7stjt2p8 2 [main.d53f5fc1.js:2:1206324](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.227 Firefox can’t establish a connection to the server at wss://relay.nostr.band/. [main.d53f5fc1.js:2:704456](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.227 Firefox can’t establish a connection to the server at wss://relay.nostr.band/all. [main.d53f5fc1.js:2:704456](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.227 Firefox can’t establish a connection to the server at wss://relay.nostr.band/. [main.d53f5fc1.js:2:704456](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.227
❌ nostr (wss://relay.nostr.band): Connection error! [main.d53f5fc1.js:2:994791](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.227 🚪 nostr (wss://relay.nostr.band): Connection closed. [main.d53f5fc1.js:2:994791](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:16.229 Uncaught (in promise) undefined 2
22:42:16.229
Uncaught (in promise) undefined [main.d53f5fc1.js:2:707738](https://nostr.band/static/js/main.d53f5fc1.js)
22:42:19.638 nostr-login options 
Object { darkMode: false, perms: "sign_event:1985,sign_event:3,sign_event:30000", dev: true }
[nostr-login.js:17:105022](https://nostr.band/nostr-login.js)
22:42:19.652 Firefox can’t establish a connection to the server at wss://purplepag.es/. [nostr-login.js:15:18650](https://nostr.band/nostr-login.js)
22:42:19.652 Firefox can’t establish a connection to the server at wss://relay.nos.social/. [nostr-login.js:15:18650](https://nostr.band/nostr-login.js)
22:42:19.652 Firefox can’t establish a connection to the server at wss://purplepag.es/. [nostr-login.js:15:18650](https://nostr.band/nostr-login.js)
22:42:19.652 Firefox can’t establish a connection to the server at wss://relay.snort.social/. [nostr-login.js:15:18650](https://nostr.band/nostr-login.js)
```

and this on Chromium:

```
router npub10r8xl2njyepcw2zwv3a6dyufj4e4ajx86hz6v4ehu4gnpupxxp7stjt2p8
nostr-login.js:17 nostr-login options ObjectdarkMode: falsedev: trueperms: "sign_event:1985,sign_event:3,sign_event:30000"[[Prototype]]: Object
main.d53f5fc1.js:2 ✅ nostr (wss://relay.nostr.band): Connected!
main.d53f5fc1.js:2 WebSocket connection to 'wss://relay.nostr.band/' failed: Error during WebSocket handshake: Unexpected response code: 502
(anonymous) @ main.d53f5fc1.js:2
f @ main.d53f5fc1.js:2
connect @ main.d53f5fc1.js:2
connect @ main.d53f5fc1.js:2
handleReconnection @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
a.onclose @ main.d53f5fc1.js:2
main.d53f5fc1.js:2 Uncaught (in promise) undefined
connect @ main.d53f5fc1.js:2
await in connect (async)
handleReconnection @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
a.onclose @ main.d53f5fc1.js:2
main.d53f5fc1.js:2 🚪 nostr (wss://relay.nostr.band): Connection closed.
VC @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
a.onclose @ main.d53f5fc1.js:2
main.d53f5fc1.js:2 WebSocket connection to 'wss://relay.nostr.band/all' failed: Error during WebSocket handshake: Unexpected response code: 502
(anonymous) @ main.d53f5fc1.js:2
f @ main.d53f5fc1.js:2
connect @ main.d53f5fc1.js:2
connect @ main.d53f5fc1.js:2
handleReconnection @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
a.onclose @ main.d53f5fc1.js:2
main.d53f5fc1.js:2 Uncaught (in promise) undefined
connect @ main.d53f5fc1.js:2
await in connect (async)
handleReconnection @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
(anonymous) @ main.d53f5fc1.js:2
a.onclose @ main.d53f5fc1.js:2
```

**Comment by franzaps** [comment]
Thanks for reporting man! But why do you say it's not working? It's doing exactly what I wanted

**Comment by Giszmo** [comment]
I'm confused. Nostr band consistently does not work for me. https://njump.me/npub10r8xl2njyepcw2zwv3a6dyufj4e4ajx86hz6v4ehu4gnpupxxp7stjt2p8 and an array of other clients would work for me.

I'm not sure how wide spread the issue is but apparently you do?

**Comment by alltheseas** [comment]
@franzaps most lightweight preview web app I have found is njump.

Consider swapping nostr band to njump.me / Zapstore-npub

**Comment by franzaps** [comment]
Sorry @Giszmo I replied without seeing the screenshot. I understand now.

So nosta.me looks like shit on mobile, nostr.band does not always load, and njump.me is even worse showing stale data. Nice.
